package ch.eiafr.enocean.telegram;

public enum CommonCommandCode {
	CO_WR_SLEEP, CO_WR_RESET, CO_RD_VERSION, CO_RD_SYS_LOG, CO_WR_SYS_LOG, CO_WR_BIST, CO_WR_IDBASE, CO_RD_IDBASE, CO_WR_REPEATER, CO_RD_REPEATER, CO_WR_FILTER_ADD, CO_WR_FILTER_DEL, CO_WR_FILTER_DEL_ALL, CO_WR_FILTER_ENABLE, CO_RD_FILTER, CO_WR_WAIT_MATURITY, CO_WR_SUBTEL, CO_WR_MEM, CO_RD_MEM, CO_RD_MEM_ADDRESS, CO_RD_SECURITY, CO_WR_SECURITY, CO_WR_LEARNMODE, CO_RD_LEARNMODE, CO_WR_SECUREDEVICE_ADD, CO_WR_SECUREDEVICE_DEL, CO_RD_SECUREDEVICES
}
