package ch.eiafr.enocean.telegram;

public enum SmartAckCommand {
	SA_WR_LEARNMODE, SA_RD_LEARNMODE, SA_WR_LEARNCONFIRM, SA_WR_CLIENTLEARNRQ, SA_WR_RESET, SA_RD_LEARNEDCLIENTS, SA_WR_RECLAIMS, SA_WR_POSTMASTER
}
